#!/bin/sh -e
# mkmaster -- tool for merging work tree back to master
# replace old patches with new ones (commits started from $START tag in work tree)
WORK=work
MASTER=master
VERSION=`grep "^Version:" *spec | sed 's/.*[ 	]//'`
NAME=`grep "^Name:" *spec | sed 's/.*[ 	]//'`
START=$WORK-$VERSION
TMPD=`mktemp -d`
PLIST="PatchList.spec.add"
PCMDS="PatchCommands.spec.add"

git checkout $WORK
# Need to define start tag (AFTER patches removal), see mkwork
git format-patch --output-directory=$TMPD $START
git checkout $MASTER

(
  cd "$TMPD"
  rm -f *.spec.add
  for P in *.patch; do
    echo "Patch${P%%-*}: $P" >> "$PLIST"
    echo "%patch${P%%-*} -p2" >> "$PCMDS"
  done
)

sed -ri "
/^Patch0+1:/r $TMPD/$PLIST
/^Patch[0-9]+:/d
/^%patch0+1 -p2/r $TMPD/$PCMDS
/^%patch[0-9]+ -p2/d
" *spec

rm -f *.patch
for N in "$TMPD"/*.patch; do
  sed -r '
  	s/^From [0-9a-f]+/From 0/
	s/^(Subject: [[]PATCH[ 0-9]*)[^]]*/\1/
	/^index [0-9a-f]+\.\.[0-9a-f]+/s/ [0-9a-f]+\.\.[0-9a-f]+ / deadbee..deadbee /
	' "$N" > `basename "$N"`
done

rm -rf "$TMPD"
